"use client"

import { useState } from "react"
import Link from "next/link"
import { toast } from "sonner"
import { ArrowLeft, BriefcaseBusiness, Check, Clipboard, Clock3, ExternalLink, Globe2, Mail, MapPin, MessageSquareText, Phone, RefreshCw, Save, Sparkles, Star } from "lucide-react"
import type { Organization } from "@/lib/admin-data"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"

export function OrganizationProfile({ organization }: { organization: Organization }) {
  const [channel,setChannel]=useState("email")
  const [tone,setTone]=useState("friendly")
  const [status,setStatus]=useState(organization.status)
  const [message,setMessage]=useState(`Здравствуйте! Меня зовут Алексей, я помогаю локальному бизнесу привлекать больше клиентов через удобные цифровые решения.\n\nОбратил внимание на ${organization.name}: у вас отличный рейтинг ${organization.rating} и много тёплых отзывов. ${organization.opportunity}\n\nМогу бесплатно показать несколько идей специально для вашего бизнеса. Будет удобно обсудить их на этой неделе?`)
  const regenerate=()=>{setMessage((current)=>current.replace("Могу бесплатно", tone === "business" ? "Предлагаю кратко обсудить" : "Буду рад бесплатно"));toast.success("Новый вариант обращения готов")}
  const copy=async()=>{await navigator.clipboard.writeText(message);toast.success("Текст скопирован")}
  return <div className="flex flex-col gap-6"><div><Button nativeButton={false} render={<Link href="/admin/search"/>} variant="ghost" size="sm"><ArrowLeft data-icon="inline-start"/>К результатам</Button></div><section className="flex flex-col gap-5 rounded-3xl border bg-card p-6 md:flex-row md:items-start md:justify-between md:p-8"><div className="flex gap-4"><span className="flex size-14 shrink-0 items-center justify-center rounded-2xl bg-primary/20 font-heading text-2xl font-bold">{organization.name.charAt(0)}</span><div><div className="flex flex-wrap items-center gap-2"><h1 className="font-heading text-3xl font-bold">{organization.name}</h1><Badge variant="secondary">{organization.category}</Badge></div><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="size-4"/>{organization.address}, {organization.city}</p><div className="mt-3 flex flex-wrap gap-2"><Badge variant="outline"><Star/>{organization.rating} · {organization.reviews} отзывов</Badge><Badge variant={organization.website ? "secondary" : "default"}>{organization.website ? "Есть сайт" : "Нет сайта"}</Badge></div></div></div><div className="flex items-center gap-3"><Select value={status} onValueChange={(value)=>setStatus((value ?? organization.status) as typeof status)}><SelectTrigger className="w-36"><SelectValue/></SelectTrigger><SelectContent><SelectGroup>{["Новый","В работе","Связались"].map(item=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectGroup></SelectContent></Select><Button variant="outline" onClick={()=>toast.success("Организация сохранена")}><Save data-icon="inline-start"/>Сохранить</Button></div></section>
  <div className="grid gap-6 xl:grid-cols-[1fr_1.35fr]"><div className="flex flex-col gap-6"><Card><CardHeader><CardTitle>Контакты и данные</CardTitle><CardDescription>Доступная информация об организации</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{[[Phone,organization.phone],[Mail,organization.email ?? "Email не найден"],[Globe2,organization.website ?? "Сайт не найден"],[BriefcaseBusiness,organization.social ?? "Соцсети не найдены"],[Clock3,organization.hours]].map(([Icon,text])=><div key={String(text)} className="flex items-center gap-3 rounded-xl bg-accent p-3 text-sm"><Icon className="size-4 shrink-0 text-muted-foreground"/><span className="truncate">{String(text)}</span>{String(text).includes("не найден") ? null : <ExternalLink className="ml-auto size-3.5 text-muted-foreground"/>}</div>)}</CardContent></Card><Card><CardHeader><CardTitle>Потенциал лида</CardTitle><CardDescription>Оценка на основе открытых данных</CardDescription></CardHeader><CardContent><div className="flex items-end justify-between"><span className="font-heading text-4xl font-bold">{organization.score}%</span><Badge>{organization.score >= 85 ? "Высокий" : "Средний"}</Badge></div><Progress value={organization.score} className="mt-3"/><div className="mt-4 rounded-xl bg-accent p-4"><p className="flex items-center gap-2 text-sm font-semibold"><Sparkles className="size-4"/>Почему стоит связаться</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{organization.opportunity}</p></div></CardContent></Card><Card><CardHeader><CardTitle>Заметки</CardTitle><CardDescription>Контекст для следующего контакта</CardDescription></CardHeader><CardContent><Textarea placeholder="Например: позвонить после 15:00, предложить аудит сайта..." rows={4}/><Button variant="outline" size="sm" className="mt-3" onClick={()=>toast.success("Заметка сохранена")}>Сохранить заметку</Button></CardContent></Card></div>
  <Card className="h-fit border-primary/40"><CardHeader><Badge className="mb-2 w-fit"><Sparkles/>AI-помощник</Badge><CardTitle className="text-xl">Персональное обращение</CardTitle><CardDescription>Сообщение учитывает данные компании и ваши услуги. Проверьте текст перед отправкой.</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><div className="grid gap-4 sm:grid-cols-2"><label className="flex flex-col gap-2 text-sm font-medium">Канал<Tabs value={channel} onValueChange={setChannel}><TabsList className="w-full"><TabsTrigger value="email" className="flex-1">Email</TabsTrigger><TabsTrigger value="messenger" className="flex-1">Мессенджер</TabsTrigger></TabsList></Tabs></label><label className="flex flex-col gap-2 text-sm font-medium">Тон<Select value={tone} onValueChange={(value)=>setTone(value ?? "friendly")}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectGroup><SelectItem value="friendly">Дружелюбный</SelectItem><SelectItem value="business">Деловой</SelectItem><SelectItem value="short">Короткий</SelectItem></SelectGroup></SelectContent></Select></label></div><Textarea value={message} onChange={(e)=>setMessage(e.target.value)} rows={14} className="leading-relaxed"/><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><Button variant="outline" onClick={regenerate}><RefreshCw data-icon="inline-start"/>Другой вариант</Button><div className="flex gap-2"><Button variant="outline" onClick={copy}><Clipboard data-icon="inline-start"/>Копировать</Button><Button onClick={()=>toast.success(channel === "email" ? "Откроем отправку после подключения backend" : "Сообщение готово к отправке")}><MessageSquareText data-icon="inline-start"/>Использовать</Button></div></div><p className="flex items-center gap-2 text-xs text-muted-foreground"><Check className="size-3.5"/>Текст можно свободно редактировать</p></CardContent></Card></div></div>
}
