"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { ArrowRight, Building2, Check, Globe2, MapPin, Phone, RotateCcw, Search, SlidersHorizontal, Star } from "lucide-react"
import { cities, niches, organizations } from "@/lib/admin-data"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Progress } from "@/components/ui/progress"
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Slider } from "@/components/ui/slider"
import { Switch } from "@/components/ui/switch"

export function SearchWorkspace() {
  const [niche, setNiche] = useState("Все ниши")
  const [city, setCity] = useState("Все города")
  const [query, setQuery] = useState("")
  const [noWebsite, setNoWebsite] = useState(false)
  const [withContacts, setWithContacts] = useState(true)
  const [rating, setRating] = useState(4)
  const [limit, setLimit] = useState(20)
  const [searched, setSearched] = useState(false)

  const results = useMemo(() => organizations.filter((item) => (niche === "Все ниши" || item.category === niche) && (city === "Все города" || item.city === city) && (!query || item.name.toLowerCase().includes(query.toLowerCase())) && (!noWebsite || !item.website) && (!withContacts || Boolean(item.phone || item.email)) && item.rating >= rating), [niche, city, query, noWebsite, withContacts, rating])
  const reset = () => { setNiche("Все ниши"); setCity("Все города"); setQuery(""); setNoWebsite(false); setWithContacts(true); setRating(4); setLimit(20); setSearched(false) }

  return <div className="flex flex-col gap-6"><header><Badge variant="secondary" className="mb-3"><Search /> Поиск лидов</Badge><h1 className="font-heading text-3xl font-bold tracking-tight">Найдите клиентов для своего бизнеса</h1><p className="mt-2 max-w-2xl text-pretty leading-relaxed text-muted-foreground">Настройте критерии — мы покажем организации с контактами и оценим потенциал каждой.</p></header>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><SlidersHorizontal className="size-5"/>Параметры поиска</CardTitle><CardDescription>Чем точнее условия, тем релевантнее результат</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="flex flex-col gap-2 text-sm font-medium">Название<Input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Например, Север" /></label><label className="flex flex-col gap-2 text-sm font-medium">Ниша<Select value={niche} onValueChange={(value)=>setNiche(value ?? "Все ниши")}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{niches.map(item=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectGroup></SelectContent></Select></label><label className="flex flex-col gap-2 text-sm font-medium">Город<Select value={city} onValueChange={(value)=>setCity(value ?? "Все города")}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{cities.map(item=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectGroup></SelectContent></Select></label><label className="flex flex-col gap-2 text-sm font-medium">Количество<Select value={String(limit)} onValueChange={(value)=>setLimit(Number(value ?? 20))}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{[10,20,50,100].map(item=><SelectItem key={item} value={String(item)}>{item} организаций</SelectItem>)}</SelectGroup></SelectContent></Select></label></div><div className="grid gap-4 border-t pt-5 md:grid-cols-3"><label className="flex items-center justify-between gap-3 rounded-xl border p-3 text-sm font-medium">Только без сайта<Switch checked={noWebsite} onCheckedChange={setNoWebsite}/></label><label className="flex items-center justify-between gap-3 rounded-xl border p-3 text-sm font-medium">Есть контакты<Switch checked={withContacts} onCheckedChange={setWithContacts}/></label><label className="flex flex-col gap-2 rounded-xl border p-3 text-sm font-medium"><span className="flex justify-between"><span>Рейтинг от</span><span>{rating.toFixed(1)}</span></span><Slider value={[rating]} min={3} max={5} step={0.1} onValueChange={(value)=>setRating(typeof value === "number" ? value : value[0] ?? 4)} /></label></div><div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button variant="ghost" onClick={reset}><RotateCcw data-icon="inline-start"/>Сбросить</Button><Button onClick={()=>setSearched(true)}><Search data-icon="inline-start"/>Найти организации</Button></div></CardContent></Card>
    <div className="flex flex-col gap-3 rounded-2xl border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Лимит тарифа Lite</p><p className="text-xs text-muted-foreground">Доступно ещё 28 организаций в этом месяце</p></div><div className="flex items-center gap-3 sm:w-72"><Progress value={72}/><span className="text-xs font-semibold">72%</span></div></div>
    {searched ? <section className="flex flex-col gap-4"><div className="flex items-end justify-between gap-4"><div><h2 className="font-heading text-2xl font-bold">Результаты</h2><p className="text-sm text-muted-foreground">Найдено {results.length} подходящих организаций</p></div><Badge variant="outline">Сначала высокий потенциал</Badge></div>{results.length ? <div className="grid gap-4 lg:grid-cols-2">{results.slice(0,limit).sort((a,b)=>b.score-a.score).map(item=><Card key={item.id} className="transition-shadow hover:shadow-md"><CardHeader><div className="flex items-start gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary/20 font-heading text-lg font-bold">{item.name.charAt(0)}</span><div className="min-w-0 flex-1"><CardTitle className="truncate">{item.name}</CardTitle><CardDescription>{item.category}</CardDescription></div><Badge variant={item.score >= 85 ? "default" : "secondary"}>{item.score}% match</Badge></div></CardHeader><CardContent className="flex flex-col gap-4"><div className="grid gap-2 text-sm text-muted-foreground sm:grid-cols-2"><span className="flex items-center gap-2"><MapPin className="size-4"/>{item.city}</span><span className="flex items-center gap-2"><Star className="size-4"/>{item.rating} · {item.reviews} отзывов</span><span className="flex items-center gap-2"><Phone className="size-4"/>{item.phone}</span><span className="flex items-center gap-2"><Globe2 className="size-4"/>{item.website ? "Есть сайт" : "Нет сайта"}</span></div><div className="flex items-center justify-between gap-3 border-t pt-4"><Badge variant="outline"><Check/>Контакты доступны</Badge><Button nativeButton={false} render={<Link href={`/admin/search/${item.id}`}/>} variant="ghost" size="sm">Подробнее <ArrowRight data-icon="inline-end"/></Button></div></CardContent></Card>)}</div> : <Card><CardContent className="flex flex-col items-center py-12 text-center"><Building2 className="size-10 text-muted-foreground"/><h3 className="mt-4 font-heading text-xl font-bold">Ничего не найдено</h3><p className="mt-1 text-sm text-muted-foreground">Попробуйте снизить рейтинг или убрать часть фильтров.</p><Button variant="outline" className="mt-4" onClick={reset}>Сбросить фильтры</Button></CardContent></Card>}</section> : <Card><CardContent className="flex flex-col items-center py-14 text-center"><span className="flex size-14 items-center justify-center rounded-2xl bg-accent"><Search className="size-6"/></span><h2 className="mt-4 font-heading text-xl font-bold">Задайте параметры и начните поиск</h2><p className="mt-1 max-w-md text-sm leading-relaxed text-muted-foreground">Результаты появятся здесь. Вы сможете открыть карточку, изучить контакты и получить AI-обращение.</p></CardContent></Card>}
  </div>
}
